import idreamersMin from "assets/icons/idreamers.min.webp";
import idreamers from "assets/icons/idreamers.webp";
import csuMin from "assets/icons/csu.min.webp";
import csu from "assets/icons/csu.webp";
import truckpediaMin from "assets/icons/truckpedia.min.webp";
import truckpedia from "assets/icons/truckpedia.webp";
import prairieMin from "assets/icons/prairie.min.webp";
import prairie from "assets/icons/prairie.webp";
import classdojoMin from "assets/icons/classdojo.min.webp";
import classdojo from "assets/icons/classdojo.webp";

const details = {
  name: {
    first: "Denis Ndaya",
    last: "Tibah",
    nickname: "Denis",
  },
  education: [
    {
      school: "University of Texas at Austin - Cockrell School of Engineering",
      url: "https://petex.utexas.edu/",
      icon: csu,
      iconMin: csuMin,
      location: "Austin, TX 78712",
      degree: "Master's Degree",
      major: "Computer science",
      start: "Sep 2006",
      end: "May 2011",
    },
  ],
  experience: [
    {
      company: "Global Solutions Link",
      icon: truckpedia,
      iconMin: truckpediaMin,
      location: "Irving,  TX",
      contract: "Contract",
      position: "Full-stack engineer",
      start: "May 2022",
      end: "Sep 2024",
      description: [],
      skills: [
        "R&D",
        "UI/UX",
        "Svelte",
        "GraphQL",
        "NodeJS",
        "Figma",
        "Flutter",
        "Java",
        "PHP",
        "Laravel",
        "AWS",
        "Python",
        "React",
        "React Native",
        "Redux",
        "NUnit",
        "Spring",
        "CI/CD",
        "Laravel",
        "Node.js",
        "Typescript",
        "AWS",
        "JSP",
        "Angular",
        "SQL",
        "PostgreSQL",
        "Next.js",
        "Nest.js",
        "Playwright",
        "C#",
        "ASP.NET",
      ],
    },
    {
      company: "Brew Apps",
      url: "https://thebrewapps.io",
      icon: prairie,
      iconMin: prairieMin,
      location: "Sheridan, WY",
      contract: "Full-time",
      position: "Front-end engineer",
      start: "Apr 2018",
      end: "May 2022",
      description: [],
      skills: [
        "DevOps",
        "Mapbox.gl",
        "Material UI",
        "Figma",
        "Vue.js",
        "Nuxt.js",
        "React",
        "Next.js",
        "GCP",
        "Laravel",
        "Three.js",
        "GraphQL",
        "Tailwind CSS",
        "Angular",
        "Typescript",
        "Databases",
        "Azure",
        "Python",
        "Django",
        "Flask",
      ],
    },
    {
      company: "Classdojo",
      url: "https://classdojo.com/",
      icon: classdojo,
      iconMin: classdojoMin,
      location: "San Francisco, CA",
      contract: "Full-time",
      position: "Full Stack Developer",
      start: "May 2016",
      end: "Apr 2018",
      description: "",
      skills: [
        "Javascript",
        "Typescript",
        "PHP",
        "Java",
        "Laravel",
        "AWS",
        "Jest",
        "Cypress",
        "Angular",
        "Python",
        "C#",
        ".NET",
        "React",
        "GCP",
        "Jenkins",
      ],
    },
    {
      company: "iDreamers",
      url: "https://www.idreamers.app/",
      icon: idreamers,
      iconMin: idreamersMin,
      location: "Los Angeles, CA",
      contract: "Freelance",
      position: "Software Engineer",
      start: "Apr 2012",
      end: "May 2016",
      description: "",
      skills: [
        "Node JS",
        "Docker",
        "GitHub CI/CD",
        "React",
        "Bootstrap",
        "Python",
        "OpenCV",
        "HTML",
        "CSS",
        "Javascript",
        "jQuery",
        "C#",
      ],
    },
  ],
  languages: [
    {
      name: "English",
      level: "C2",
      native: true,
    },
    {
      name: "Chinese",
      level: "B2",
    },
  ],
  contact: {
    address: "Seagoville, TX 75159",
    email: "denis.tibah0218@gmail.com",
    phone: "323-521-4182",
    website: "https://denis-tibah.vercel.app",
    linkedin: "https://www.linkedin.com/in/denis-tibah-885b44314",
    github: "https://github.com/denis-tibah",
    stackoverflow: "https://stackoverflow.com/users/22221109/secret-point",
  },
};

export default details;
